version: '3'

volumes:
  ignore_dir:

services:
  app:
    build: .
    image: kouwasi/rails-docker
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./:/app
      - ignore_dir:/app/tmp
      - ignore_dir:/app/public
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: webpacker

  webpacker:
    image: kouwasi/rails-docker
    command: ./bin/webpack-dev-server
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    depends_on:
      - app
    volumes:
      - .:/app
    ports:
      - 3035:3035

  db:
    restart: always
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db/data:/var/lib/postgresql/data